Enable correct RPM calculation
doppelhub/MuddersMIMA pull request #2
Opened 2023-12-19 19:15 UTC by Hurricos

The two commits in this PR enable correct RPM calculation, which was not working before.

- fix: rpm: Count QTY3 ignition pulses per QTY2 revolutions
- fix: rpm: Enable pin-change IRQs on port B

Tested-by: Martin Kennedy <hurricos@gmail.com>

### Addenda
I should probably write up a more complete testing procedure so I can document an A/B test.

2024-01-31 02:45 UTC, Hurricos commented
Here is my complete A/B test of each of these commits:

Test procedure for e69d832ce08c7b72398149d7e28ec54ebe8b23c4 (RPM fixup pull request):
- `git checkout e69d83`
- Compiled and sent firmware
- In ASM, `$DISP=OEM` to start seeing OEM values, including RPM
- Insert key on fully cold engine
- Start car, note output:
```console
21:31:43.389 -> MAMODE2:Reg/Idle, MAMODE1:Prestart, CLUTCH:Pressed,  BRAKE:Released, CMDPWR:49% TPS:7% MAP:55% RPM:0
21:31:43.655 -> MAMODE2:Assist,   MAMODE1:Starting, CLUTCH:Pressed,  BRAKE:Released, CMDPWR:49% TPS:8% MAP:52% RPM:0
21:31:43.922 -> MAMODE2:Assist,   MAMODE1:Starting, CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:38% RPM:1034
21:31:44.155 -> MAMODE2:Assist,   MAMODE1:Starting, CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:27% RPM:1336
21:31:44.421 -> MAMODE2:Assist,   MAMODE1:Starting, CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:22% RPM:1751
21:31:44.654 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:19% RPM:1801
21:31:44.920 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:7% MAP:18% RPM:1727
21:31:45.153 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:19% RPM:1650
21:31:45.419 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:19% RPM:1577
21:31:45.652 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:20% RPM:1581
```
- `git checkout 1c6cfe9` (the commit before: this includes the change-request pin enablement fixup, but not the conversion from pulse to RPM):
- Compiled and sent firmware
- In ASM, `$DISP=OEM` to start seeing OEM values, including RPM
- Insert key on fully cold engine
- Start car, note output:
```console
21:32:26.377 -> MAMODE2:Assist,   MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:55% RPM:0
21:32:26.643 -> MAMODE2:Assist,   MAMODE1:Starting, CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:43% RPM:897
21:32:26.876 -> MAMODE2:Assist,   MAMODE1:Starting, CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:26% RPM:1969
21:32:27.142 -> MAMODE2:Assist,   MAMODE1:Starting, CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:21% RPM:2373
21:32:27.374 -> MAMODE2:Reg/Idle, MAMODE1:AutoStop, CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:7% MAP:19% RPM:2535
21:32:27.641 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:19% RPM:2411
21:32:27.907 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:19% RPM:2405
21:32:28.140 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:20% RPM:2397
21:32:28.405 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:20% RPM:2404
```
My engine was for sure idling at 1600RPM cold.
To test 1c6cfe9 ("fix: rpm: Enable pin-change IRQs on port B") to make sure enabling pin-change interrupts was needed, I did:
- `git checkout 6d2b793a2ac06ecc8f13460337834970078e7dd2` (the current `main` branch on doppelhub/MuddersMIMA.git):
- Compiled and sent firmware
- In ASM, `$DISP=OEM` to start seeing OEM values, including RPM
- Insert key on fully cold engine
- Start car, note output:
```console
21:39:36.841 -> MAMODE2:Reg/Idle, MAMODE1:Prestart, CLUTCH:Pressed,  BRAKE:Released, CMDPWR:49% TPS:8% MAP:55% RPM:0
21:39:37.074 -> MAMODE2:Assist,   MAMODE1:Starting, CLUTCH:Pressed,  BRAKE:Released, CMDPWR:49% TPS:8% MAP:49% RPM:0
21:39:37.340 -> MAMODE2:Assist,   MAMODE1:Starting, CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:31% RPM:0
21:39:37.573 -> MAMODE2:Assist,   MAMODE1:Starting, CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:23% RPM:0
21:39:37.839 -> MAMODE2:Assist,   MAMODE1:Starting, CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:18% RPM:0
21:39:38.072 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:19% RPM:0
21:39:38.338 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:20% RPM:0
21:39:38.570 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:19% RPM:0
21:39:38.836 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:19% RPM:0
21:39:39.069 -> MAMODE2:Reg/Idle, MAMODE1:Standby,  CLUTCH:Released, BRAKE:Released, CMDPWR:49% TPS:8% MAP:19% RPM:0
```

2024-06-02 07:49 UTC, doppelhub requested changes
Can you optimize the "2/3" math, so the preprocessor only has to perform one division operation?  Ideally '2' & '3' are both #define statements, too, so that they aren't magic numbers.  Proposed implementation: "(ONE_MINUTE_IN_MICROSECONDS * ENGINE_REVOLUTIONS / NUM_TACHOMETER_PULSES) / periodBetweenTicks_us".  The preprocessor will perform all constant-only math if it's all grouped together.

2024-06-03 15:56 UTC, Hurricos commented
> Can you optimize the "2/3" math, so the preprocessor only has to perform one division operation? Ideally '2' & '3' are both #define statements, too, so that they aren't magic numbers. Proposed implementation: "(ONE_MINUTE_IN_MICROSECONDS * ENGINE_REVOLUTIONS / NUM_TACHOMETER_PULSES) / periodBetweenTicks_us". The preprocessor will perform all constant-only math if it's all grouped together.

Done in commit a3f07010d2c54cef7d47a523ea9c4201bbf4217b. For other readers, godbolt.org with AVR GCC 13.2.0 and with flags -Os has this function going down from 0x92 bytes to 0x80 bytes: [godbolt.org](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYMQkgEykHAGTwGTAA5dwAjTGIQAHZSAAdUBUJbBmc3Dy9fROSbAUDgsJZI6LjLTGtUoQImYgJ0908fC0wrPIZq2oIC0Iio2IsauobM5oUh7qDe4v6YgEoLVFdiZHYOAFJvAGYg5DcsAGp1rcdx/EEAOgRj7HWNAEE7x%2B2sGmCDgAkASQBxD4OuE9MKoCFEGAdXEECFtvMYCAdgPFbMZGMApgAlZQAWWMwEwBGUQU6oIgc2OACEgSCwRCoTC4QcWHhkMQkqSKU8AG4uJg2ei0wRcABsDIMoPG2CMGOxRy2ABEDhoOQ9NltXlMDgB5ELYYxYr4hOQAFV1Br1X0c6M1Qmwjm1cqEBy2Qo0GmwQqeTwA9F7lI4sUIANIaA54BQHNAMGjAZaYdAHBSoA4EBC8g4CWgATwOcoAHBGmK4lOGoVFiK54vCIAoK4k6uG8yA5VwtmSHty8PGmOyVTFKQ8DoOEzUbMgBdDYfCasgEKg2KDiEbmQBrYzxYiYTm2IvGIuyhVKrb9x4aACceCo0CRqBRUuCmJxeIJRJHmFJ%2B%2BOCog3z%2BczbJ9PdY%2B09M87lPSFBHpKcmBnOd8SiJdkFXBhUAAd13cNP0ZZlWQUdkjxAgCwKHccoIOeIolsdByXxVDMEYRDlwUDD92TGDZ3nBCV2MFD0L3ABaNjYM4xduPXTdt2YotlRPIizxIsVMAlO9MAfVjtV1fVDRNYwzX1S1rVte1HS9A4IAo4gqJogg6IYlcpPDAAqJ0DlM7wyQIgcSKHQiwLA6cOPg0SkLXDctyWBzWICuCF0Yni0IwmS/JiOVPRSjgFloTgAFZeE8bheFQThHATJYVkwI5th4UgCE0DKFmXEBvGy/ROEkPK6tIIqOF4BQQA0Gq6oWOBYBgRAUDnJF6DICgIDQFgpv6UROWIYAW28AaaFoBc%2BogcJOGq8IglqTMDt4I7mGITNNXCbQKlqjgtFIea2EETUGCzTqsHCVxgEcMRaD6grSCwFhDGAcRHt4fAN0qTklLOvxVAqVxQUR0ssqh/Q8HCYgTucLBEYISyWER%2BHiHCJJMDlTAwaMWgglAKGFioAxgAUAA1PBMFQzUKPy6r%2BEEEQxHYKQZEERQVHULHdC4fRwZAUxjHMBnwj6yAFlQStUiB/jNQUQrycsrANdJFo2lSewGCcFxGj0AIpiKEo9ByFIBBGTx5bd9oemd/p5fKSoBE6YY7cyQPWnuqoJj9vpokDiZPb0cYujjmYE4WRNllWCRMpyjqse6g57g59EEWQMcWwubwLhDCBcEIEhKq2Lg5l4B6tD/UgEEwJgsGic3GuygbMfa0hSZiXMLi4DRJGymJsuFLYtlPXMhVPUh8qe7rev6wbmdIEbxqWAh4lR8h7HwIgTb0IXhFEcRxfvqW1E6uXSFQvH4jO/OOFyrenVuqalRufeEqAqAlzLhXKuWwa51zMs4BadAogtzbh3IaCxe7936ObMevBSbeC4BcXMp5so%2BEkLmZ0LoWwaFzIAounA94DU7vVUgjVmqtQ4FsQuO8mEHy7kfMaEAkBoCwI3G%2Bl9qAoOYGwRG98RZP2kC/JQb9ZZNQVkYJWZgLbRzsBABwycpBxEdoUeOTVvZJHdmkcOXtJBxB9qkdOLsiG6ODh0JOtiJD2Lce0UOkwzEZwsYMLoRifGpzqM4/oRCs5lVzhsbYux9gVWOKcAg5wCBXBuL5F4mA3gVR/P8QEDxgQLnBBBCcDJETIlRNKR8%2BJCQeN5G%2BDyx5Sk0gqWRJkLI2StK5DyPkFUKnClFM05SaJ7wyiwoeY8qp1TvA0uabSpoQjmgMjaO0IQHROhdG6D0Kpcn5IOIaHE2AQg/ANLqdE2AOaan8MaL42ohDGGUNgdExhHAAE1HD%2BGwAcbwnpDkahOcYI09xHAfE1FibAJp3nKDkP4G0zzXnvK%2BT8v5WxCI%2Bj9AGYMoZwyRmjLGeMiZkypnAR9bMeYCxFiUqGQQZYKxVhrPEOsBAGy5ibC2f8/TOwHG7Dy4CXlByp1HKRScQlAqxTEmFSSLFplJTPBeK8NSVIPlxA0l8zT3yfiwt%2BX4Hw/wgUAkKuS4E6QSuiiJOKvF5Xymwj0vCfSVQusAvJIcnSJUWSsrReiDBGKRSwlaoKNqEoCUlTFLiIVxLhR3NJTyZqFJjIIJKCZqkpn2ogIsrSxoVlrKtBs4yBxnIgrORcnUxhrm3PuUaR5IRkVvI%2Bd835rljlyBxGCiFUKYWNvhYi7ADbUXNuwHMVt3qMDWVsv6%2ByiUE3eR8i6s1wbpXRtlRFO1Cpl1RuQmGhQiqTWpV7HKDKXCAHb0KsVUqOcUnbG8Bg5mDUmqSAuKeV9b733vqFFw8e56ur8L6iwoaQj4AiImsg6aUj5qLWiMtVa61Np0B2pQfaWMLonURmhq6N07rWE6i9RgBB3qfSxt9X6/1aCA0RqDcGkMnow2jvDIGT1gQozRsDDGnU1Z4yugTNYT1iZ4FJsDcmlMlA0zphDRmQHWZMHZlzHmfNGDyNkIosWyjZCvxlk9XQvgDBaOVqrHGZstY6wEHrA2RsyydgRprXxVsDE2yMX4G2USE4JCse0Jzjj8hO3MZHS2IdPEZC9nZwLadfNBMTqErxUXIkRZdm3RY16mp/zPUAzgUDy7AErgCOBtd64SObqqdy96u6Ps4fghhfCeoWH3qw7umM71VYvTV%2BrCxybJDsJIIAA) 

Given that this is an ISR that runs once per engine pulse, these are important savings.

2024-06-17 05:18 UTC, doppelhub approved these changes
Glad to get this into main!

2024-06-17 05:19 UTC, merged